#!/bin/bash
cd "$(dirname "$0")"
if [ -a ~/Library/Application\ Support/minecraft/CraftNCraft ]
	then
		echo Looks like CraftNCraft folder is created, using it
	else
		mkdir ~/Library/Application\ Support/minecraft/CraftNCraft
fi
echo Installing Forge Mods.....
cp -a -f ./Modpack\ Resources/ForgeMods ~/Library/Application\ Support/minecraft/CraftNCraft/mods
echo Forge Mods Installed
echo Installing Liteloader Mods.....
cp -a -f ./Modpack\ Resources/LiteloaderMods ~/Library/Application\ Support/minecraft/CraftNCraft/mods/1.8
echo Liteloader Mods Installed
echo Installing Forge.....
mkdir ~/Library/Application\ Support/minecraft/versions/Forge
cp ./Modpack\ Resources/Forge/ClientJSON.json ~/Library/Application\ Support/minecraft/versions/Forge/Forge.json
echo Everything Done!!!
exit